import { MetadataInfo } from './../../../@pika/metadata/metadata-info';
export const MetadataElemento: MetadataInfo =
{
    "AsociadoMetadatos": true,
    "TokenApp": "PIKA-GD-CONTENIDO",
    "TokenMod": "ESTRUCTURA-CONTENIDO",
    "Tipo": "Elemento",
    "FullName": "PIKA.Modelo.Contenido.Elemento",
    "ElminarLogico": true,
    "PaginadoRelacional": false,
    "ColumaEliminarLogico": "Eliminada",
    "Propiedades": [
        {
            "Id": "Id",
            "Nombre": "Id",
            "TipoDatoId": "string",
            "ValorDefault": "",
            "Requerido": false,
            "EsIndice": false,
            "Buscable": true,
            "Ordenable": true,
            "Visible": false,
            "IndiceOrdenamiento": 0,
            "EsIdClaveExterna": false,
            "EsIdRegistro": true,
            "EsIdJerarquia": false,
            "EsTextoJerarquia": false,
            "EsIdRaizJerarquia": false,
            "EsFiltroJerarquia": false,
            "Autogenerado": false,
            "OrdenarValoresListaPorNombre": true,
            "ControlHTML": null,
            "IndiceOrdenamientoTabla": 0,
            "Etiqueta": false,
            "Contextual": false,
            "IdContextual": null,
            "MostrarEnTabla": true,
            "AlternarEnTabla": true,
            "TipoDato": null,
            "AtributoLista": null,
            "AtributosEvento": [],
            "AtributosVistaUI": [
                {
                    "PropiedadId": "Id",
                    "Control": "hidden",
                    "Accion": 2,
                    "Plataforma": "web"
                }
            ],
            "ValidadorTexto": null,
            "ValidadorNumero": null,
            "ParametroLinkVista": {
                "Vista": "visorcontenido"
            }
        },
        {
            "Id": "Nombre",
            "Nombre": "Nombre",
            "TipoDatoId": "string",
            "ValorDefault": "",
            "Requerido": true,
            "EsIndice": false,
            "Buscable": true,
            "Ordenable": true,
            "Visible": true,
            "IndiceOrdenamiento": 10,
            "EsIdClaveExterna": false,
            "EsIdRegistro": false,
            "EsIdJerarquia": false,
            "EsTextoJerarquia": false,
            "EsIdRaizJerarquia": false,
            "EsFiltroJerarquia": false,
            "Autogenerado": false,
            "OrdenarValoresListaPorNombre": true,
            "ControlHTML": null,
            "IndiceOrdenamientoTabla": 10,
            "Etiqueta": false,
            "Contextual": false,
            "IdContextual": null,
            "MostrarEnTabla": true,
            "AlternarEnTabla": true,
            "TipoDato": null,
            "AtributoLista": null,
            "AtributosEvento": [],
            "AtributosVistaUI": [
                {
                    "PropiedadId": "Nombre",
                    "Control": "textbox",
                    "Accion": 3,
                    "Plataforma": "web"
                }
            ],
            "ValidadorNumero": null,
            "ParametroLinkVista": {
                "Vista": "visorcontenido"
            }
        },
        {
            "Id": "Eliminada",
            "Nombre": "Eliminada",
            "TipoDatoId": "bool",
            "ValorDefault": "true",
            "Requerido": false,
            "EsIndice": false,
            "Buscable": true,
            "Ordenable": true,
            "Visible": true,
            "IndiceOrdenamiento": 50,
            "EsIdClaveExterna": false,
            "EsIdRegistro": false,
            "EsIdJerarquia": false,
            "EsTextoJerarquia": false,
            "EsIdRaizJerarquia": false,
            "EsFiltroJerarquia": false,
            "Autogenerado": false,
            "OrdenarValoresListaPorNombre": true,
            "ControlHTML": null,
            "IndiceOrdenamientoTabla": 50,
            "Etiqueta": false,
            "Contextual": false,
            "IdContextual": null,
            "MostrarEnTabla": true,
            "AlternarEnTabla": true,
            "TipoDato": null,
            "AtributoLista": null,
            "AtributosEvento": [],
            "AtributosVistaUI": [
                {
                    "PropiedadId": "Eliminada",
                    "Control": "none",
                    "Accion": 0,
                    "Plataforma": "web"
                }
            ],
            "ValidadorTexto": null,
            "ValidadorNumero": null,
            "ParametroLinkVista": null
        },
        {
            "Id": "CreadorId",
            "Nombre": "CreadorId",
            "TipoDatoId": "string",
            "ValorDefault": "",
            "Requerido": false,
            "EsIndice": false,
            "Buscable": true,
            "Ordenable": true,
            "Visible": false,
            "IndiceOrdenamiento": 1000,
            "EsIdClaveExterna": false,
            "EsIdRegistro": true,
            "EsIdJerarquia": false,
            "EsTextoJerarquia": false,
            "EsIdRaizJerarquia": false,
            "EsFiltroJerarquia": false,
            "Autogenerado": false,
            "OrdenarValoresListaPorNombre": true,
            "ControlHTML": null,
            "IndiceOrdenamientoTabla": 1000,
            "Etiqueta": false,
            "Contextual": false,
            "IdContextual": null,
            "MostrarEnTabla": true,
            "AlternarEnTabla": true,
            "TipoDato": null,
            "AtributoLista": {
                "PropiedadId": "CreadorId",
                "OrdenarAlfabetico": false,
                "Entidad": "PropiedadesUsuario",
                "DatosRemotos": true,
                "TypeAhead": false,
                "Default": "",
                "ValoresCSV": "",
                "Valores": [], 
                "Endpoint": "api/v1.0/seguridad/usuarios/"
            },
            "AtributosEvento": [],
            "AtributosVistaUI": [
                {
                    "PropiedadId": "CreadorId",
                    "Control": "hidden",
                    "Accion": 0,
                    "Plataforma": "web"
                }
            ],
            "ValidadorTexto": null,
            "ValidadorNumero": null,
            "ParametroLinkVista": null
        },
        {
            "Id": "FechaCreacion",
            "Nombre": "FechaCreacion",
            "TipoDatoId": "datetime",
            "ValorDefault": "",
            "Requerido": false,
            "EsIndice": false,
            "Buscable": true,
            "Ordenable": true,
            "Visible": false,
            "IndiceOrdenamiento": 1010,
            "EsIdClaveExterna": false,
            "EsIdRegistro": true,
            "EsIdJerarquia": false,
            "EsTextoJerarquia": false,
            "EsIdRaizJerarquia": false,
            "EsFiltroJerarquia": false,
            "Autogenerado": false,
            "OrdenarValoresListaPorNombre": true,
            "ControlHTML": null,
            "IndiceOrdenamientoTabla": 1010,
            "Etiqueta": false,
            "Contextual": false,
            "IdContextual": null,
            "MostrarEnTabla": true,
            "AlternarEnTabla": true,
            "TipoDato": null,
            "AtributoLista": null,
            "AtributosEvento": [],
            "AtributosVistaUI": [
                {
                    "PropiedadId": "FechaCreacion",
                    "Control": "datetime",
                    "Accion": 2,
                    "Plataforma": "web"
                }
            ],
            "ValidadorTexto": null,
            "ValidadorNumero": null,
            "ParametroLinkVista": null
        },
        {
            "Id": "VolumenId",
            "Nombre": "VolumenId",
            "TipoDatoId": "string",
            "ValorDefault": "",
            "Requerido": false,
            "EsIndice": false,
            "Buscable": true,
            "Ordenable": true,
            "Visible": true,
            "IndiceOrdenamiento": 70,
            "EsIdClaveExterna": false,
            "EsIdRegistro": false,
            "EsIdJerarquia": false,
            "EsTextoJerarquia": false,
            "EsIdRaizJerarquia": false,
            "EsFiltroJerarquia": false,
            "Autogenerado": false,
            "OrdenarValoresListaPorNombre": true,
            "ControlHTML": null,
            "IndiceOrdenamientoTabla": 70,
            "Etiqueta": false,
            "Contextual": false,
            "IdContextual": null,
            "MostrarEnTabla": true,
            "AlternarEnTabla": true,
            "TipoDato": null,
            "AtributoLista": {
                "PropiedadId": "VolumenId",
                "OrdenarAlfabetico": false,
                "Entidad": "Volumen",
                "DatosRemotos": true,
                "TypeAhead": false,
                "Default": "",
                "ValoresCSV": "",
                "Valores": [],
                "Endpoint": "api/v1.0/contenido/volumen/"
            },
            "AtributosEvento": [],
            "AtributosVistaUI": [
                {
                    "PropiedadId": "VolumenId",
                    "Control": "select",
                    "Accion": 1,
                    "Plataforma": "web"
                }
            ],
            "ValidadorTexto": null,
            "ValidadorNumero": null,
            "ParametroLinkVista": {
                "Vista": "visorcontenido"
            }
        },
        {
            "Id": "Versionado",
            "Nombre": "Versionado",
            "TipoDatoId": "bool",
            "ValorDefault": "true",
            "Requerido": false,
            "EsIndice": false,
            "Buscable": true,
            "Ordenable": true,
            "Visible": false,
            "IndiceOrdenamiento": 1010,
            "EsIdClaveExterna": false,
            "EsIdRegistro": false,
            "EsIdJerarquia": false,
            "EsTextoJerarquia": false,
            "EsIdRaizJerarquia": false,
            "EsFiltroJerarquia": false,
            "Autogenerado": false,
            "OrdenarValoresListaPorNombre": true,
            "ControlHTML": null,
            "IndiceOrdenamientoTabla": 1010,
            "Etiqueta": false,
            "Contextual": false,
            "IdContextual": null,
            "MostrarEnTabla": false,
            "AlternarEnTabla": false,
            "TipoDato": null,
            "AtributoLista": null,
            "AtributosEvento": [],
            "AtributosVistaUI": [
                {
                    "PropiedadId": "Versionado",
                    "Control": "hidden",
                    "Accion": 3,
                    "Plataforma": "web"
                }
            ],
            "ValidadorTexto": null,
            "ValidadorNumero": null,
            "ParametroLinkVista": null
        },
        {
            "Id": "VersionId",
            "Nombre": "VersionId",
            "TipoDatoId": "string",
            "ValorDefault": "",
            "Requerido": false,
            "EsIndice": false,
            "Buscable": true,
            "Ordenable": true,
            "Visible": false,
            "IndiceOrdenamiento": 1010,
            "EsIdClaveExterna": false,
            "EsIdRegistro": false,
            "EsIdJerarquia": false,
            "EsTextoJerarquia": false,
            "EsIdRaizJerarquia": false,
            "EsFiltroJerarquia": false,
            "Autogenerado": false,
            "OrdenarValoresListaPorNombre": true,
            "ControlHTML": null,
            "IndiceOrdenamientoTabla": 1010,
            "Etiqueta": false,
            "Contextual": false,
            "IdContextual": null,
            "MostrarEnTabla": true,
            "AlternarEnTabla": false,
            "TipoDato": null,
            "AtributoLista": null,
            "AtributosEvento": [],
            "AtributosVistaUI": [
                {
                    "PropiedadId": "VersionId",
                    "Control": "hidden",
                    "Accion": 2,
                    "Plataforma": "web"
                }
            ],
            "ValidadorTexto": null,
            "ValidadorNumero": null,
            "ParametroLinkVista": {
                "Vista": "visorcontenido"
            }
        }
    ],
    "EntidadesVinculadas": [],
    "CatalogosVinculados": [],
    "VistasVinculadas": [
        {
            "Vista": "visorcontenido",
            "Icono": "preview",
            "Titulo": "visor",
            "RequiereSeleccion": true,
            "Tipo": 0
        },
        {
            "Vista": "buscarcontenido",
            "Icono": "manage_search",
            "Titulo": "buscarcontenido",
            "RequiereSeleccion": false,
            "Tipo": 0
        }
    ],
    "Reportes": []
}
